# Generated by Django 3.1.7 on 2021-10-10 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
        ('authentication', '0003_auto_20211010_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_status', models.BooleanField(default=False)),
                ('percentage_completion', models.PositiveSmallIntegerField(default=0)),
                ('payment_iters', models.PositiveSmallIntegerField(default=0, verbose_name='Payment Iterations')),
                ('total_paid_amount', models.PositiveIntegerField(default=0)),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='authentication.member')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='job.project')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='authentication.startup')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update_message', models.TextField(max_length=2048)),
                ('update_percentage', models.PositiveSmallIntegerField(default=0)),
                ('approval', models.BooleanField(default=False)),
                ('accept', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.accept')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='authentication.member')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tansaction_id', models.CharField(default='', max_length=20)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('percent', models.PositiveSmallIntegerField(default=0, verbose_name='Completion Percentage At Payment')),
                ('accept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.accept')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1_ans', models.TextField(max_length=1024)),
                ('q2_ans', models.TextField(max_length=1024)),
                ('q3_ans', models.TextField(max_length=1024)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.project')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.startup')),
            ],
        ),
    ]
