# Generated by Django 3.1.7 on 2021-10-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accept',
            old_name='completion_status',
            new_name='completed',
        ),
        migrations.AlterField(
            model_name='bid',
            name='q1_ans',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='bid',
            name='q2_ans',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='bid',
            name='q3_ans',
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
