# Generated by Django 3.1.7 on 2021-10-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='role',
            field=models.PositiveIntegerField(choices=[(2, 'startup'), (1, 'admin'), (3, 'member')], default=3),
        ),
    ]
