# Generated by Django 3.1.7 on 2021-03-31 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='company_code',
            field=models.PositiveIntegerField(unique=True, verbose_name='DTWWLNG'),
        ),
    ]
