# Generated by Django 3.1.7 on 2021-10-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211010_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='role',
            field=models.PositiveIntegerField(choices=[(3, 'member'), (2, 'startup'), (1, 'admin')], default=3),
        ),
    ]
