# Generated by Django 3.1.7 on 2021-03-31 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210401_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='company_code',
            field=models.PositiveIntegerField(unique=True, verbose_name='PSJWOSM'),
        ),
    ]
