# Generated by Django 3.1.7 on 2021-10-10 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20211010_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='startup',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='authentication.startup'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='role',
            field=models.PositiveIntegerField(choices=[(3, 'member'), (1, 'admin'), (2, 'startup')], default=3),
        ),
    ]
