# Generated by Django 3.1.7 on 2021-04-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210401_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='company_code',
            field=models.CharField(default='FEUJMIP', max_length=7, unique=True),
        ),
    ]
