# Generated by Django 3.1.7 on 2021-04-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210401_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='team_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='startup',
            name='company_code',
            field=models.CharField(default='XBIVBDT', max_length=7, unique=True),
        ),
    ]
