# Generated by Django 3.1.7 on 2021-10-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20210401_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='company_code',
            field=models.CharField(default='DODTXAV', max_length=7, unique=True),
        ),
    ]
