# Generated by Django 3.1.7 on 2021-10-10 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_auto_20211010_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Add Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=250)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('deadline', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=35)),
                ('cost', models.CharField(max_length=128)),
                ('q1', models.CharField(default='', max_length=512)),
                ('q2', models.CharField(default='', max_length=512)),
                ('q3', models.CharField(default='', max_length=512)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.startup')),
                ('tags', models.ManyToManyField(to='job.Tag')),
            ],
        ),
    ]
